import { Library } from "./types";

export const SAMPLE_LIBRARIES: Library[] = [
  {
    id: "1",
    name: "shadcn/ui",
    slug: "shadcn-ui",
    description:
      "Beautifully designed components built with Radix UI and Tailwind CSS",
    framework: "React",
    website_url: "https://ui.shadcn.com",
    github_url: "https://github.com/shadcn-ui/ui",
    stars: 75000,
    logo_url: "/file.svg",
    tags: ["components", "tailwind", "radix"],
  },
  {
    id: "2",
    name: "Aceternity UI",
    slug: "aceternity-ui",
    description: "Copy-paste beautiful UI components built with Tailwind",
    framework: "React",
    website_url: "https://ui.aceternity.com",
    github_url: "https://github.com/aceternity/ui",
    stars: 12000,
    logo_url: "/globe.svg",
    tags: ["components", "tailwind"],
  },
  {
    id: "3",
    name: "Magic UI",
    slug: "magic-ui",
    description: "Animated UI components for React and Tailwind CSS",
    framework: "React",
    website_url: "https://magicui.design",
    github_url: "https://github.com/magicuidesign/magicui",
    stars: 4800,
    logo_url: "/window.svg",
    tags: ["components", "animation", "react"],
  },
  {
    id: "4",
    name: "Tamagui",
    slug: "tamagui",
    description: "Universal React design system and component library",
    framework: "React",
    website_url: "https://tamagui.dev",
    github_url: "https://github.com/tamagui/tamagui",
    stars: 13000,
    logo_url: "/globe.svg",
    tags: ["design-system", "react", "cross-platform"],
  },
  {
    id: "5",
    name: "Radix UI",
    slug: "radix-ui",
    description: "Low-level UI primitives for building design systems",
    framework: "React",
    website_url: "https://www.radix-ui.com",
    github_url: "https://github.com/radix-ui/primitives",
    stars: 23000,
    logo_url: "/globe.svg",
    tags: ["primitives", "accessibility", "react"],
  },
  {
    id: "6",
    name: "Headless UI",
    slug: "headless-ui",
    description:
      "Completely unstyled, fully accessible UI components (Tailwind Labs)",
    framework: "React",
    website_url: "https://headlessui.com",
    github_url: "https://github.com/tailwindlabs/headlessui",
    stars: 41000,
    logo_url: "/globe.svg",
    tags: ["components", "accessibility", "react"],
  },
  {
    id: "7",
    name: "Chakra UI",
    slug: "chakra-ui",
    description: "Simple, modular and accessible component library for React",
    framework: "React",
    website_url: "https://chakra-ui.com",
    github_url: "https://github.com/chakra-ui/chakra-ui",
    stars: 35000,
    logo_url: "/globe.svg",
    tags: ["components", "react", "accessible"],
  },
  {
    id: "8",
    name: "Mantine",
    slug: "mantine",
    description: "Fully featured React components library",
    framework: "React",
    website_url: "https://mantine.dev",
    github_url: "https://github.com/mantinedev/mantine",
    stars: 48000,
    logo_url: "/globe.svg",
    tags: ["components", "react"],
  },
  {
    id: "9",
    name: "Ant Design",
    slug: "ant-design",
    description:
      "Enterprise-class UI design language and React UI library",
    framework: "React",
    website_url: "https://ant.design",
    github_url: "https://github.com/ant-design/ant-design",
    stars: 95000,
    logo_url: "/globe.svg",
    tags: ["components", "react", "enterprise"],
  },
];

export const FRAMEWORKS = ["All", "React", "Vue", "Svelte", "Solid"];

export const TAGS = [
  "components",
  "tailwind",
  "radix",
  "animation",
  "react",
  "design-system",
  "cross-platform",
  "primitives",
  "accessibility",
  "accessible",
  "enterprise",
];